#if defined _voiceannounceex_included_
	#endinput
#endif
#define _voiceannounceex_included_


/**
 * Return Current Map's Property of Banning Human Skills
 * @return	True if Current Map Banned Human Skills
 */
native bool RY_MapProperty_BanHumanSkills();

/**
 * Return Current Map's Property of Banning Zombie Skills
 * @return	True if Current Map Banned Zombie Skills
 */
native bool RY_MapProperty_BanZombieSkills();

/**
 * Return Current Map's Property of Banning JK Function
 * @return	True if Current Map Banned JK Functiom
 */
native bool RY_MapProperty_BanJK();

/**
 * Return Current Map's Property of Bhop Limit
 * @return	True if Current Map Set no limit to bhop
 */
native bool RY_MapProperty_NoBhopLimit();



